name: universal_datastores
description: Dart package which manages data stores are commonly used.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  equatable: ^2.0.5
  freezed_annotation: ^2.4.4
  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
